theme: jekyll-theme-time-machine
title: MkWeb
description: Servlet Based Web Server Framework
baseurl: https://mkweb.dev-whoan.xyz
show_list: true
link1: true
link1_uri: /configs
link1_label: Configs
link2: true
link2_uri: /views
link2_label: Views
link3: true
link3_uri: /sqls
link3_label: Sqls
link4: true
link4_uri: /apis
link4_label: REST API
link5: true
link5_uri: /ftp
link5_label: FTP
link6: true
link6_uri: /jwt
link6_label: JWT